# This workflow will build and deploy the site
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on: push
env:
  STORAGE_ACCOUNT_NAME: lulc
  CDN_PROFILE_NAME: lulc
  CDN_ENDPOINT: lulcstaging.azureedge.net
  RESOURCE_GROUP: lulcStaging
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Install
        run: yarn install
        
      - name: Build
        run: yarn build
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
              az storage blob upload-batch --account-name $STORAGE_ACCOUNT_NAME -d '$web' -s ./dist

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name $CDN_PROFILE_NAME --name $CDN_ENDPOINT --resource-group $RESOURCE_GROUP
            
      - name: Azure Logout
        run: az logout