name: Invoke workflow in another repo with inputs
  uses: benc-uk/workflow-dispatch@v1
  with:
    workflow: frontend-staging.yml
    repo: developmentseed/pearl-reforestamos-deploy
    inputs: '{ "message": "blah blah", "something": false }'
    token: ${{ secrets.PAT }}
